---
title: "warm_up_02"
author: "JIEUN HWANG"
date: "9/15/2017"
output: github_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# assembling url (so it fits on the screen)
github <- 'https://github.com/ucb-stat133/stat133-hws-fall17/'
repo <- 'raw/master/warmup02/data/nba2017-salary-points.RData'

download.file(
  url = paste0(github, repo),
  destfile = "nba2017-salary-points.RData")
```

```{r}
# load the objects
load("nba2017-salary-points.RData")

# list the available objects
ls()
```
```{r}
class(player)
is.factor(team)
is.factor(player)
is.vector(points)
is.list(repo)
length(player)
length(position)
class(points)

# What flavor is each vector (i.e. variable)?


```

```{r}
summary(points)
hist(points)
boxplot(points)

# What are the typical values in each vector?
# What's the spread in each vector?

```

```{r}
factor(team)
table(team)
table(factor(position))
barplot(frequency(position))
# You can also try to get a density curve (or density polygon). Find out how to do this.

#Find out how to use the obtained frequency table to calculate relative frequencies (proportions).
#Use the frequencies (counts) and relative frequencies (proportions) to describe the overall distribution.#

```

# Report your process 
```{r}
## What things were hard, even though you saw them in class?
 # I have hard time getting used to R and use syntax 
## What was easy(-ish) even though we haven't done it in class?
  # N/A
## What type of "errors" you struggled with (if any)?
  # N/A
## What are the parts you are not fully understanding?
  # data type and vector
## What was the most time consuming part?
  # lab 2
## Did you collaborate with other students? If so, with who? In what manner?
  # not really but I asked some questions to GSI
## Was there any frustrating issue? (e.g. RStudio cryptic error, one or more package not playing nice)
  # N/A
```

